export const add = (a, b) => a + b;

export { default as Anchor } from './src/Anchor'
export { default as Badge } from './src/Badge'
export { default as Block } from './src/Block'
export { default as Button } from './src/Button'
export { default as Card } from './src/Card'
export { default as Field } from './src/Field'
export { default as Heading } from './src/Heading'
export { default as Icon } from './src/Icon'
export { default as IconButton } from './src/IconButton'
export { default as Input } from './src/Input'
export { default as Label } from './src/Label'
export { default as Menu } from './src/Menu'
export { default as Modal } from './src/Modal'
export { default as P } from './src/P'
export { default as Select } from './src/Select'
